### PR TITLE
Accesibility milestone to portfolio

### PR DESCRIPTION
**Pull request by Gdiazdiaz**
Dear Code Review team,
Could you please help us to review the following changes made to the Porfolio project related to Accessibility features, which are the following:

###  Report
- [x] Page titles -*no issues found.*
- [x] Image text alternatives -*no issues found.*
- [x] Text headings -*no issues found.*
- [x] Color contrast -*change the font color from white to black on all buttons.* [line 392 on styles.css](https://github.com/luigirazum/mv-portfolio-project/pull/8/files#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L392) and
[line 770 on styles.css](https://github.com/luigirazum/mv-portfolio-project/pull/8/files#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L770)
- [x] Resize -*no issues found.*
- [x] Interaction -*add a label to all form elements (name, email, message).* [line 287-304 on index.html](https://github.com/luigirazum/mv-portfolio-project/pull/8/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R287-R304)
- [x] Moving content -*set animation duration to 4s and delete infinite iteration.* [line 143-145 on styles.css](https://github.com/luigirazum/mv-portfolio-project/pull/8/files#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L143-L145)
- [x] Multimedia -*no issues found.*
- [x] The basic structure of the page -*no issues found.*

Some of these changes were done as suggested by [Wave Accessibility Evaluation Tool](https://wave.webaim.org/report#/https://luigirazum.github.io/#) Report.

We really appreciate your kindly support.
Cheers,
Glenda / Luis

### CODE REVIEW

**Review by ridwanediallo — CHANGES_REQUESTED** [review]
# Changes Required ♻️
## Hi team, 
AlmostThereReachGIF

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


## Required Changes ♻️
- [ ]  Hey team, good job so far. However, the colour contrast on your buttons is failing. Please make sure to fix it. Open this [link](https://www.aditus.io/button-contrast-checker/luigirazum-github-io-2022-11-08-at-18-55-55-940?failing) to get the details. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by luigirazum** [comment]
Dear Code Review Team,
The required changes were applied.
Could you help us with your review.

Thanks in advance.
Cheers,
Glenda / Luis

**Comment by ridwanediallo** [comment]
Please submit for another review.

**Review by 1GORDON — APPROVED** [review]
# Status: APPROVED 🟢 

Hi @Gdiazdiaz & @luigirazum ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️

## Optional suggestions

- [ ] Kindly remove the author that did not contribute to this PR from the Readme file. This makes your readme file and projects more professional.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
